### ISSUE TITLE
** نشست رایگان تکنولوژی های نوین وب **

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#244]
<div dir='rtl'>
سلام خدمت همه ی دوستان<br/>
<br/>
به بهانه ی شروع دوره های جدید، <b>نشست رایگان تکنولوژی های نوین وب</b> و توضیح در مورد کلاس ها، عصر دوشنبه ۴ دی ماه برگزار میشود.<br/>
<br/>
لطفا جهت رزرو و هماهنگی های بعدی فرم ali.md/reserve را تکمیل فرمایید.<br/>
با توجه به محدودیت در تعداد شرکت کنندگان, آدرس و ساعت برگزاری پس از تایید رزرواسیون شما، sms خواهد شد.<br/>
دوستانی که زودتر فرم را تکمیل کنند در اولویت خواهند بود.<br/>
لطفا به دیگر دوستان علاقه مند نیز اطلاع دهید.<br/>
<br/>
با عرض پوزش از خانم ها این نشست ویژه آقایان میباشد ولی می توانید با ارسال نماینده و یا دریافت فایل صوتی از مباحث استفاده کنید.<br/>
<br/>
در صورت نیاز به اطلاعات بیشتر میتوانید در ساعات اداری با جناب آقای صداقت (09153049373) تماس بگیرید.<br/>
<br/>
<br/>
با تشکر<br/>
علی میهن دوست
</div>

**Comment by sahbaee** [comment]
@AliMD Ostad 2Shanbe Saat 20:30 ta 22:30  okeye?
 :)))

**Comment by hbehkamal** [comment]
be nazar manam oun time khoobe :)) man sabt e nam kardam amma address ersal nashod. @AliMD

**Comment by alimd** [comment]
حالا شما شوخی میکنید
ولی ما واقعا بعد 9 سال دوباره شروع کردیم
و این دوشنبه هم کلاس داریم 😎

**Comment by hbehkamal** [comment]
نایس. تبریک. این دوشنبه که گذشت؟ آدرس بدید اگه شد سر بزنیم.

**Comment by msedaghat110** [comment]
> نایس. تبریک. این دوشنبه که گذشت؟ آدرس بدید اگه شد سر بزنیم.

باز هم بعد از ۹ سال باید با آقای صداقت هماهنگ کنی😉

**Comment by alimd** [comment]
مگه شماها اینو ندیدین!!
https://t.me/AliMDSchool/204
