### ISSUE TITLE
I AM NOT A ROBOT !

### ISSUE THREAD

**Issue by alimd** [AliMD/1Tuts#552]
Github ye payame jaleb behem dade !

One of our mostly harmless robots seems to think you are not a human.
Because of that, it's hidden your profile from the public. If you really are human, please contact support to have your profile reinstated.
We promise we won't require DNA proof of your humanity.

elat hazf shodane movaghate profile man ham hamin bood !
fekr konam bi rabt be karaue omidgharib nabashe !

**Comment by hhsadiq** [comment]
I also got this exact problem. They blocked my profile from public. I reported this problem at support and profile was restored in less than half an hour. I think github guys have programmed their NOT SO HARMLESS robot with some weird too-strict rules. They definitely need to revise their policy, it is giving too many false positives.

**Comment by alimd** [comment]
@hhsadiq You must submit your request to github not here
