### ISSUE TITLE
کمپین جمع آوری امضاء برای برگزاری دوره های جدید

### ISSUE THREAD

**Issue by Alirezahp** [AliMD/1Tuts#661]
همانطور که مستحضر هستید برگزاری دوره های کلاس استاد میهن دوست فعلا برگزار نمیشود و از آنجایی که بین دوره فاصله ی زیادی افتاده است تقریبا بسیاری از مطلب فراموش شده است.
لذا هدف از ایجاد این ایشو برای جمع آوری امضا و اعتراض برای برگزاری هر چه سریعتر دوره ها می باشد.
هر چند که میدانیم باز هم استاد گرامی محل نمیگذارد اما ما همچنان هستیم و خواستار برگزاری هر چه سریعتر دوره ها مباشیم.
با تچکر
@AliMD 
@hoseinBL

**Comment by ahmad59** [comment]
man ham manotazere shoroe kelasa hastam

**Comment by mahdvi** [comment]
claaaaaaaaaaaaaaaaaaasssssssssssssssssssssss

**Comment by mahdvi** [comment]
miiiiiiiiiiiiiiiiiiiiiiiiiiiikhhhhhhhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaaaiiiiiiiiiiiiiiimmmmmmmmmmmmmm

**Comment by mahdvi** [comment]
loooooooooooooooooooooooooooootttttttttttttttttttffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnnnnnnnnnnn

**Comment by mahdvi** [comment]
aaaaaaaaaaaaaaaggggggghhhhhhaaaayeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by mahdvi** [comment]
miiiiiiiiiiihhhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaannnnnnnnnnnnnddddddddooooooooooooosssssssssttttttttttttttttttt

**Comment by mahdvi** [comment]
lllllllooooooooooooooooffffffffffffffffffttttttttttttttttttaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnnnnnnnnnnnnnnnnnn

**Comment by AliMD** [comment]
سلام
مگر از این بی خرید ؟!!!
http://ali.md/onecast

**Comment by mahdvi** [comment]
ostad kharabe ke

**Comment by AliMD** [comment]
برای من درسته که
با VPN و یا بات telegram.me/onecast_bot تست کن
مشکلی داشت با ذکر کامل مشکل بهم ایمیل کن
ممنون

**Comment by mahdvi** [comment]
ostad hanoz natonestam bebinam

hamin soal ro lodfan javab bedin : class baz ham mizarid aya ???

**Comment by AliMD** [comment]
are, faghat be soorat online, va felan faghat onecast
jeddan class be naf shoma nist va in onecast ha besiyar mofidtare

**Comment by alimd** [comment]
یادش بخیر
بیاین بعد این همه سال شروع شد
https://t.me/AliMDSchool/204
