### ISSUE TITLE
یه قولی بدین استاد!

### ISSUE THREAD

**Issue by rezamahan** [AliMD/1Tuts#662]
#### سلام استاد؛

سه چهار روز دیگه ماه رمضون تموم میشه به سلامتی. امیدوارم اون پروژه هم به خوبی و خوشی پیش رفته باشه...
حالا دیگه بیشتر از این ماها رو چشم انتظار نذارین تروخدا :cry: 
#### یه قولی برای برگذاری کلاس بدین لااقل از این چشم انتظاری دربیایم!

ثواب داره به خدا :smile:

**Comment by alimd** [comment]
قول

https://t.me/AliMDSchool/204
