### ISSUE TITLE
سلام استاد سلام کلاس سلام

### ISSUE THREAD

**Issue by AminAzGol** [AliMD/1Tuts#664]
سلام بر جناب استاد میهن دوست  و دیگر دوستان 
استاد از شما خاهشمندیم که در یکی از ایشو هه حضور پیدا کرده و خبری نسبت به کلاس ها اراعه فرمایید و یک جمع را از انتظار بیرون بکشید 
ما بی صبرانه منتظر کامنت شما هستیم 
@AliMD 
:ear:

**Comment by alimd** [comment]
سلام
https://t.me/AliMDSchool/204
