### ISSUE TITLE
پرداخت درون برنامه ای برای وب اپلیکیشن ها

### ISSUE THREAD

**Issue by hoseinBL** [AliMD/1Tuts#665]
سلام

من میخواستم برای یک `وب اپلیکیشن` مثل اپ های `نی تیو` پرداخت درون برنامه ای داشته باشم.

پیشنهاد شما چیه؟ اصن میشه؟ (البته کار نشد نداره)

خودم یک سایت پیدا کردم که پرداخت های موبایلی رو از طریق `یو اس اس دی` انجام میده. ازین روش میشه واسه اپلیکیشن ها هم استفاده کرد؟

تنکس عین عــَــد وَنس :smile:

**Comment by MAgolestani** [comment]
ono vel kon agha yadesh bekhair parsal ye hamchin ayami class miraftim

**Comment by AliMD** [comment]
سلام
اگر داری hybrid مینویسی که میشه و فرقی با native نداره
باید روش native رو بلد باشی و کامل بنویسی و فقط از طریق javascript  فراخانی
کنیش
شیوه ی فراخانی کردن هم مبحث جدایی هست که تو مبحث cordova plugin پیداش میکنی
