### ISSUE TITLE
I am not a robot!!!

### ISSUE THREAD

**Issue by bybai** [AliMD/1Tuts#668]
I received this in the page;
But I am not a robot, I am xCAT developer,https://github.com/xcat2/xcat-core/. It is urgent for me to get my account back.
Could you help me?

One of our mostly harmless robots seems to think you are not a human.
Because of that, it's hidden your profile from the public. If you really are human, please contact support to have your profile reinstated.
We promise we won't require DNA proof of your humanity.

**Comment by AliMD** [comment]
:open_mouth:
