### ISSUE TITLE
HTML/CSS Courses

### ISSUE THREAD

**Issue by AliMD** [AliMD/1Tuts#669]
Collection of top HTML/CSS course in the worlds

**Comment by AliMD** [comment]
the most popular but not good enough
www.w3schools.com/html

**Comment by AliMD** [comment]
The right way: http://htmlcsstherightway.org/

**Comment by berenjian** [comment]
https://www.codeschool.com/paths/html-css 

Codeschool teach HTML and CSS together

**Comment by mohammadn** [comment]
HTML and CSS for beginners:
https://www.codeschool.com/courses/front-end-foundations

HTML 5:
https://www.codeschool.com/courses/front-end-formations

**Comment by berenjian** [comment]
http://www.tutorialspoint.com/html/

**Comment by berenjian** [comment]
http://www.lynda.com/HTML-training-tutorials/224-0.html

**Comment by berenjian** [comment]
https://www.codecademy.com/learn/web

**Comment by berenjian** [comment]
https://developer.mozilla.org/en-US/Learn/HTML

**Comment by berenjian** [comment]
https://www.w3.org/2002/03/tutorials.html#webdesign_htmlcss

**Comment by berenjian** [comment]
http://learn.shayhowe.com/html-css/

**Comment by AliMD** [comment]
for start: https://docs.webplatform.org/wiki/Beginners

**Comment by berenjian** [comment]
http://www.htmldog.com/guides/html/

**Comment by mohammadn** [comment]
very good and complete ref:
http://html5doctor.com/

**Comment by mohammadn** [comment]
ebook (!free):
http://ebook-dl.com/item/html5_for_web_designers_jeremy_keith/

**Comment by berenjian** [comment]
http://www.quackit.com/html/tutorial/ 
not bad ...

**Comment by mohammadn** [comment]
HTML tricks(kheyli bahash hal kardam) :
http://www.html5rocks.com/en/

**Comment by berenjian** [comment]
Cool tuturial :+1:  (Open with VPN :/ )
https://www.khanacademy.org/computing/computer-programming/html-css
https://www.khanacademy.org/computing/computer-programming/html-css/intro-to-html/p/html-basics#

**Comment by AliMD** [comment]
https://docs.webplatform.org/wiki/html/tutorials
